spring:
  datasource:
    url: jdbc:mysql://localhost:5426/user_management?characterEncoding=utf8&useSSL=false
    username: root
    password: #密码
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: #端口
    host: 127.0.0.1
    password: #密码
  web:
    resources:
      static-locations: classpath:static/,file:static/

logging:
  file:
    name: user_management.log
  level:
    com:
      example:
        demo: error


server:
  port: 8081