spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_management?characterEncoding=utf8&useSSL=false
    username: root
    password: #密码
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: #端口
    host:  #ip
    password: #密码

logging:
  file:
    name: user_management.log
  level:
    com:
      example:
        demo: debug

server:
  port: 8080