spring:
  datasource:
    url: jdbc:mysql://localhost:5426/blog_system?characterEncoding=utf8&useSSL=false
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 
    host: 127.0.0.1
    password: 
  web:
    resources:
      static-locations: classpath:static/,file:static/

logging:
  file:
    name: blog-system.log
  level:
    com:
      example:
        demo: error


server:
  servlet:
    context-path: /blog
  port: 8080

