spring:
  datasource:
    url: jdbc:mysql://localhost:5426/blog_system?characterEncoding=utf8&useSSL=false
    username: root
    password: 983024@JK~xiazhu
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 9574
    host: 127.0.0.1
    password: 10086@JK~toxiazhu536402
  web:
    resources:
      static-locations: classpath:static/,file:static/

logging:
  file:
    name: blog-system.log
  level:
    com:
      example:
        demo: error


server:
  servlet:
    context-path: /blog
  port: 8080
#server:
#  port: 5454
# 本机ip : 117.140.185.49 /117.140.184.108
