spring:
  session:
    store-type: redis
    timeout: 1800  # 单位是秒
    redis:
      namespace: spring:session # 设置redis的命名空间
      flush-mode: on_save # redis的刷新模式为在保存时刷新,表示在session数据保存到redis时会刷新过期时间
  profiles:
    #active: testwindows
    active: testlinux
  web:
    resources:
      static-locations: classpath:static/,file:static/
  servlet:
    multipart:
      max-file-size: 20MB # 单个文件大小
      max-request-size: 20MB #单次请求文件总大小


server:
  servlet:
    context-path: /blog
  port: 8080

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/blog_system?characterEncoding=utf8&useSSL=false
#    username: root
#    password: 983024@JK~xiazhu # 983024@JK~xiazhu # windows 1234 #linux 983024@JK~xiazhu
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  redis:
#    port: 9574
#    host: 62.234.10.69
#    password: 10086@JK~toxiazhu536402
#  session:
#    store-type: redis
#    timeout: 1800  # 单位是秒
#    redis:
#      namespace: spring:session
#      flush-mode: on_save
#  profiles:
#    active: testwindows

#  web:
#    resources:
#      static-locations: classpath:/static/

mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


