spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_system?characterEncoding=utf8&useSSL=false
    username: root
    password: 1234 # 983024@JK~xiazhu # windows 1234 #linux 983024@JK~xiazhu
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 9574
    host:  62.234.10.69
    password: 10086@JK~toxiazhu536402

logging:
  file:
    name: blog-system.log
  level:
    com:
      example:
        demo: debug

server:
  port: 8080
 # 本机ip : 117.140.185.49
  #117.140.184.108
  # cidr段 117.140.184.0 - 117.140.185.255 =117.140.184/8+8+7=23
  #110000100
  #110000101

