spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_system?characterEncoding=utf8&useSSL=false
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 
    host:  
    password: 

logging:
  file:
    name: blog-system.log
  level:
    com:
      example:
        demo: debug

server:
  port: 8080


